<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // Telegram Bot API base URL. Rossiyada Telegram bloklangani uchun
    // Cloudflare Worker proxy orqali ishlaymiz. Default: https://api.telegram.org
    'api_url' => env('TELEGRAM_API_BASE_URL', 'https://api.telegram.org'),

    // HTTP client umumiy timeout (sekund). Proxy zanjiri (server -> worker -> Telegram)
    // sekin bo'lsa ham bitta job uzoq osilib qolmasligi uchun past tutamiz. 30s juda
    // baland edi: sekin chaqiruv butun queue worker'ni bloklaydi.
    'client_timeout' => (int) env('TELEGRAM_CLIENT_TIMEOUT', 12),

    // Ulanish (connect) timeout — proxy/Telegram javob bermasa tez fail bo'ladi,
    // to'liq read timeout kutib o'tirmaydi. Transient retry shu zahoti qayta uriadi.
    'connect_timeout' => (int) env('TELEGRAM_CONNECT_TIMEOUT', 5),

    // Telegram -> server yo'nalishi uchun webhook base URL.
    // Telegram Rossiyadagi serverga to'g'ridan-to'g'ri ulana olmasa, bu URL Cloudflare
    // Worker domeni bo'ladi (worker /webhook/* ni ORIGIN_URL ga proxy qiladi).
    // Bo'sh bo'lsa APP_URL ishlatiladi. Misol: https://your-worker.workers.dev
    'webhook_base_url' => env('TELEGRAM_WEBHOOK_BASE_URL', ''),

    // Cloudflare Worker bilan shared secret. Worker server -> Telegram yo'nalishida
    // X-Proxy-Secret header tekshiradi (faqat bizning serverdan kelgan so'rovlar o'tadi).
    'proxy_secret' => env('TELEGRAM_PROXY_SECRET', ''),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    // Cloudflare Worker proxy orqasida turganda IP tekshiruvi yolg'on positive beradi.
    'safe_mode' => env('TELEGRAM_SAFE_MODE', false),

    // Extra or specific configurations
    'config' => [],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
];
